name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Get latest tag version
      id: vars
      run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Package
  env:
    RELEASE_VERSION: ${{ env.tag }}
  run: |
    echo "Release version: $RELEASE_VERSION"
    dotnet pack -p:PackageVersion=$RELEASE_VERSION
    dotnet nuget push DotPrompt.Sql/nupkg/*.nupkg -k ${{ secrets.AZURECODER_NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

